# Generated by Django 5.0 on 2024-01-02 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Actor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Genre",
            fields=[
                ("genre_id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="IMDBEntry",
            fields=[
                (
                    "imdb_id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Director",
            fields=[
                (
                    "director_id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=255)),
                ("birth_year", models.IntegerField(blank=True, null=True)),
                ("death_year", models.IntegerField(blank=True, null=True)),
                ("primary_profession", models.CharField(max_length=255)),
                ("known_for_titles", models.ManyToManyField(to="tmdbData.imdbentry")),
            ],
        ),
        migrations.CreateModel(
            name="Movies",
            fields=[
                ("tmdb_id", models.IntegerField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("vote_average", models.FloatField()),
                ("vote_count", models.IntegerField()),
                ("release_date", models.CharField(max_length=50)),
                ("runtime", models.IntegerField()),
                ("adult", models.BooleanField()),
                ("revenue", models.BigIntegerField()),
                ("budget", models.BigIntegerField()),
                ("overview", models.TextField()),
                ("casts", models.ManyToManyField(to="tmdbData.actor")),
                (
                    "directors",
                    models.ManyToManyField(
                        related_name="movies", to="tmdbData.director"
                    ),
                ),
                ("genres", models.ManyToManyField(to="tmdbData.genre")),
                (
                    "imdb_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tmdbData.imdbentry",
                    ),
                ),
            ],
        ),
    ]
